name: Multi Verion Check

on:
  pull_request:

permissions:
  contents: read

jobs:
   build:
    strategy:
      matrix:
        php: [ '8.0', '8.1', '8.2' ]
        phpunit: [ '8.0', '9.0', '10.0' ]
        exclude:
          - php: '8.0'
            phpunit: '10.0'

    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }}, PHPUnit ${{ matrix.phpunit }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, json 
        ini-values: error_reporting=E_ALL
        coverage: pcov
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Declare required PHPUnit version
      run: |
        composer require --no-update phpunit/phpunit ~${{ matrix.phpunit }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-dev

    - name: Run test suite
      run: composer run-script test:unit
